sudo: required
services:
  - docker

before_install:
  - docker pull node:8-onbuild

install:
  - docker build -t docker-hello .

script:
  - docker run --rm docker-hello npm run test
  - docker run --rm docker-hello npm run lint

after_success:
  - docker tag docker-hello docker-hello:$(git rev-parse HEAD)
